# Generated by Django 5.2 on 2025-04-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='last_connected',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_disconnected',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
