# Generated by Django 5.2 on 2025-07-03 04:52

import detection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_alter_device_last_connected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='file_path',
            field=models.FileField(upload_to=detection.models.Image.image_upload_to),
        ),
    ]
